// Package env handles serialisation of Vault secrets into .env files.
//
// # Overview
//
// The Writer type is the primary entry point. It accepts a map of
// string key/value pairs (typically produced by the vault and filter
// packages) and writes them to a local .env file in a deterministic,
// sorted order.
//
// # Backup behaviour
//
// When the backup option is enabled, any pre-existing .env file is
// copied to a timestamped ".bak" file in the same directory before
// the new file is written. This prevents accidental data loss during
// a sync operation.
//
// # File format
//
// The generated file follows the de-facto .env convention:
//
//	# Generated by vaultpipe on <RFC3339 timestamp>
//	KEY=value
//	KEY_WITH_SPACES="value with spaces"
//
// Values that contain whitespace characters are automatically
// double-quoted so that common .env parsers handle them correctly.
package env
