// Package env provides utilities for writing secrets to .env files.
package env

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// Writer writes key-value secret pairs to a .env file.
type Writer struct {
	path    string
	backup  bool
}

// NewWriter creates a new Writer targeting the given file path.
// If backup is true, an existing file will be backed up before overwriting.
func NewWriter(path string, backup bool) *Writer {
	return &Writer{path: path, backup: backup}
}

// Write serializes the provided secrets map into the .env file.
// Keys are written in sorted order for deterministic output.
func (w *Writer) Write(secrets map[string]string) error {
	if w.backup {
		if err := w.backupExisting(); err != nil {
			return fmt.Errorf("env: backup failed: %w", err)
		}
	}

	f, err := os.Create(w.path)
	if err != nil {
		return fmt.Errorf("env: create file %q: %w", w.path, err)
	}
	defer f.Close()

	fmt.Fprintf(f, "# Generated by vaultpipe on %s\n", time.Now().UTC().Format(time.RFC3339))

	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		v := secrets[k]
		if strings.ContainsAny(v, " \t\n") {
			v = fmt.Sprintf("%q", v)
		}
		if _, err := fmt.Fprintf(f, "%s=%s\n", k, v); err != nil {
			return fmt.Errorf("env: write key %q: %w", k, err)
		}
	}

	return nil
}

// backupExisting copies the current file to a timestamped backup path.
func (w *Writer) backupExisting() error {
	if _, err := os.Stat(w.path); os.IsNotExist(err) {
		return nil
	}
	data, err := os.ReadFile(w.path)
	if err != nil {
		return err
	}
	backupPath := fmt.Sprintf("%s.%d.bak", w.path, time.Now().Unix())
	return os.WriteFile(backupPath, data, 0600)
}
